sudo: false
language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
  - "npm install -g velocity-cli"
script:
  - "karma start"
  - "velocity test-package ./ --ci"