sudo: false
language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
before_install:
  - "curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh"
before_script:
  - "export PATH=$HOME/.meteor:$PATH"
script:
  - "npm run eslint"
  - "npm run test:karma"
  - "npm run test:velocity"
after_success:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"