sudo: required
language: node_js
cache:
  directories:
    # cache node modules
    - node_modules
notifications:
  # disable email notification
  email: false
node_js:
  # use same node version as meteor does
  - "0.12"
before_install:
  # use firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  # remove unused node modules from cache
  - "npm prune"
script:
  # run karma
  - "npm run test"
after_success:
  # send code-coverage report to coveralls
  - "npm run coverage:coveralls"
